#!/usr/bin/env node

/**
 * Post-install script that automatically creates a custom Gemini Gem
 * when the power is first installed in Kiro.
 */

import fs from "fs/promises";
import path from "path";
import { execSync } from "child_process";

async function postInstall() {
    console.log("\n🎨 UI Designer & Design-to-Code Power - Post-Install Setup\n");

    // Check if this is first install (no gem-config.json exists)
    const configPath = path.join(process.cwd(), ".kiro", "gem-config.json");

    try {
        await fs.access(configPath);
        console.log("✅ Custom Gem configuration already exists");
        console.log("   Use 'Regenerate my custom Gem' to update it\n");
        return;
    } catch {
        // Config doesn't exist, this is first install
    }

    console.log("📦 First-time setup detected!");
    console.log("   A custom Gemini Gem will be automatically created for your project.\n");

    console.log("🔍 Auto-detecting your project structure...");
    console.log("   - Scanning for design system files");
    console.log("   - Looking for component examples");
    console.log("   - Reading steering files\n");

    console.log("✨ Your custom Gem will be named:");

    // Try to get project name
    let projectName = "Project";
    try {
        const packageJson = await fs.readFile("package.json", "utf-8");
        const pkg = JSON.parse(packageJson);
        projectName = pkg.name || "Project";
    } catch {
        // Try git
        try {
            const repoUrl = execSync("git config --get remote.origin.url", { encoding: "utf-8" }).trim();
            const match = repoUrl.match(/\/([^\/]+?)(\.git)?$/);
            projectName = match ? match[1] : "Project";
        } catch {
            // Use default
        }
    }

    console.log(`   "UI Designer Pro - ${projectName}"\n`);

    // Auto-detect files
    console.log("🔍 Scanning project structure...");
    const designSystemFiles = [];
    const codebaseExamples = [];

    // Search for design system files
    const designSystemPaths = ["design-system", "docs/design-system", "design", "styles/design-system"];
    for (const dsPath of designSystemPaths) {
        try {
            const files = await fs.readdir(dsPath);
            for (const file of files) {
                if (file.endsWith(".md")) {
                    designSystemFiles.push(path.join(dsPath, file));
                }
            }
        } catch {
            // Directory doesn't exist
        }
    }

    // Search for component files
    const componentPaths = ["src/components", "components", "src/ui", "ui"];
    for (const compPath of componentPaths) {
        try {
            const files = await fs.readdir(compPath);
            const componentFiles = files
                .filter(f => f.endsWith(".tsx") || f.endsWith(".ts") || f.endsWith(".jsx") || f.endsWith(".js"))
                .slice(0, 5);

            for (const file of componentFiles) {
                codebaseExamples.push(path.join(compPath, file));
            }

            if (codebaseExamples.length > 0) break;
        } catch {
            // Directory doesn't exist
        }
    }

    console.log(`   ✅ Found ${designSystemFiles.length} design system files`);
    console.log(`   ✅ Found ${codebaseExamples.length} component examples`);
    console.log(`   ✅ Steering files will be scanned on first use\n`);

    // Create initial configuration
    const config = {
        gemName: `UI Designer Pro - ${projectName}`,
        designSystemFiles,
        codebaseExamples,
        customInstructions: null,
        generatedAt: new Date().toISOString(),
        projectName,
        autoGenerated: true,
    };

    // Save configuration
    const configDir = path.join(process.cwd(), ".kiro");
    try {
        await fs.mkdir(configDir, { recursive: true });
        await fs.writeFile(configPath, JSON.stringify(config, null, 2));
        console.log("💾 Configuration saved to .kiro/gem-config.json\n");
    } catch (error) {
        console.error("⚠️  Could not save configuration:", error.message);
    }

    console.log("✨ Custom Gem configuration created automatically!");
    console.log(`   Gem name: "UI Designer Pro - ${projectName}"\n`);

    console.log("🚀 The power will use this configuration automatically.");
    console.log("   No manual setup needed - just start using it!\n");

    console.log("📝 Optional commands:");
    console.log("   - 'Show my Gem configuration' - View current config");
    console.log("   - 'Regenerate my custom Gem' - Update after changes\n");

    console.log("✅ Installation complete!\n");
}

postInstall().catch(error => {
    console.error("Error during post-install:", error);
    process.exit(0); // Don't fail the installation
});
